
[GlobalSettings]
MarkOfTheWebBox=Discord
Template=7zipShellEx
Template=Edge_Fix
Template=OfficeLicensing
Template=OnScreenKeyboard
Template=WindowsLive
Template=WindowsRasMan
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=y
SandboxieLogon=y
DefaultBox=DefaultBox
LockBoxToUser=y
MonitorStackTrace=n
EditAdminOnly=y

[UserSettings_1DE8035E]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_EnableAutoStart=y
BoxGrouping=:Discord,DefaultBox

[Template_Local_SharedTemplate]
Tmpl.Title=Shared Template
Tmpl.Class=Local
#DisableWizardSettings=n
#RemoveDefaultAll=n
#RemoveDefaultRecovers=n
#RemoveDefaultTemplates=n
Tmpl.Comment=Add your settings after this line.

[Discord]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#0423ee,ttl,6,192,in,6
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
Template=Chrome_KB5027231_fix
Template=LessConfidentialBox
ConfigLevel=10
UseFileImage=y
ConfidentialBox=y
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoDeleteSnapshotTarget=Default
UseSecurityMode=y
UsePrivacyMode=y
EditAdminOnly=y
BreakoutProcess=msedge.exe
OpenPipePath=C:\Users\megatron\Downloads
OpenPipePath=D:\Sandboxie\Icons
LockBoxToUser=y
OpenFilePath=C:\Users\megatron\Documents

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#00FFFF,ttl
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
ConfigLevel=10

