
[GlobalSettings]
MarkOfTheWebBox=Discord
Template=7zipShellEx
Template=Edge_Fix
Template=OfficeLicensing
Template=OnScreenKeyboard
Template=WindowsLive
Template=WindowsRasMan
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=y
SandboxieLogon=y
DefaultBox=DefaultBox
LockBoxToUser=y
MonitorStackTrace=n
EditAdminOnly=y

[UserSettings_1DE8035E]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
SbieCtrl_EnableAutoStart=y
BoxGrouping=:Discord
SbieCtrl_HideMessage=2205,ConsoleInit (C00000D4)

[Template_Local_SharedTemplate]
Tmpl.Title=Shared Template
Tmpl.Class=Local
#DisableWizardSettings=n
#RemoveDefaultAll=n
#RemoveDefaultRecovers=n
#RemoveDefaultTemplates=n
Tmpl.Comment=Add your settings after this line.

[Discord]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#0423ee,ttl
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
Template=Chrome_KB5027231_fix
ConfigLevel=10
UsePrivacyMode=y
UseSecurityMode=y
UseFileImage=y
ConfidentialBox=y
UseFileDeleteV2=y
UseRegDeleteV2=y
FakeAdminRights=y
SandboxieLogon=y
ProtectHostImages=y
OpenPipePath=D:\Sandboxie\discord-sandbox\scripts\shared\
OpenPipePath=%UserProfile%\Downloads\
OpenFilePath=%UserProfile%\Downloads\
OpenPipePath=%UserProfile%\Documents\
OpenFilePath=%UserProfile%\Documents\
OpenPipePath=D:\Sandboxie\Icons
BreakoutProcess=msedge.exe
UseWin32kHooks=y
OpenFilePath=%LocalAppData%\Discord\
OpenFilePath=%TEMP%\
ForceProcess=%LocalAppData%\Discord\Update.exe
ForceProcess=Discord.exe

